version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: rtree_postgres
    environment:
      POSTGRES_DB: spatial_search_db
      POSTGRES_USER: spatial_user
      POSTGRES_PASSWORD: spatial_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - spatial_network

  redis:
    image: redis:7-alpine
    container_name: rtree_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spatial_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rtree_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spatial.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - spatial_network

volumes:
  postgres_data:
  redis_data:

networks:
  spatial_network:
    driver: bridge